/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package molpadia_streaming_media_webapp;

import org.junit.Test;
import static org.junit.Assert.*;

public class ApplicationTest {

}
